### PR TITLE
add CLA check

### PR DESCRIPTION
**Pull request by delgod**
Check if Canonical's Contributor License Agreement has been signed by the PR author(s).

### CODE REVIEW

**Comment by taurus-forever** [comment]
@delgod it looks like you are not passing CLA check.
BTW, any manuals how to sign it? We will need to give the link to community members PR us. :-D

**Comment by marceloneppel** [comment]
> @delgod it looks like you are not passing CLA check. BTW, any manuals how to sign it? We will need to give the link to community members PR us. :-D

There is a manual on Juju about that: https://github.com/juju/juju/blob/3.3/CONTRIBUTING.md#contributor-licence-agreement

**Comment by delgod** [comment]
> > @delgod it looks like you are not passing CLA check. BTW, any manuals how to sign it? We will need to give the link to community members PR us. :-D
> 
> There is a manual on Juju about that: https://github.com/juju/juju/blob/3.3/CONTRIBUTING.md#contributor-licence-agreement

the problem here, that [Guideline says](https://github.com/juju/juju/blob/3.3/CONTRIBUTING.md#contributor-licence-agreement)
> you can't use the @users.noreply.github.com email that GitHub provides).

but our repo requires to use GitHub noreply email 😞

**Review by taurus-forever — APPROVED** [review]
LGTM!

CC: @carlcsaposs-canonical should it be part of https://github.com/canonical/data-platform-workflows ?

**Review by marceloneppel — APPROVED** [review]

**Review by deusebio — APPROVED** [review]

**Pull request merged**
