### PR TITLE
S3 Improvements

### LINKED ISSUE #463: WAL archiving disables after primary changes
## Steps to reproduce

1. `juju deploy s3-integrator`, and configure it
2. `juju deploy postgresql --channel edge --config profile=testing -n 3`
3. `juju integrate postgresql s3-integrator`
4. `juju ssh postgresql/0 sudo cat /var/snap/charmed-postgresql/current/etc/patroni/patroni.yaml | grep archive`
  For each unit, it will show `archive_command: 'pgbackrest --config=/var/snap/charmed-postgresql/current/etc/pgbackrest/pgbackrest.conf --stanza=dev.postgresql archive-push %p'`
6. `juju remove-unit postgresql/2` - but choose your primary
7. Wait until cluster stabilizes
8. Do the step 4, but now see `archive_command: /bin/true` in the output for each unit

## Expected behavior
Archiving is still enabled after primary changes

## Actual behavior

Archiving is disables after primary changes

## Versions

Operating system: Ubuntu 23.10

Juju CLI: 3.4.2-genericlinux-amd64

Juju agent: 3.4.0

Charm revision: 405

LXD: 5.21.1 LTS

## Log output

Juju debug log: [log.txt](https://github.com/canonical/postgresql-operator/files/15229007/log.txt)

## Additional context
I found that stanza is being erased from app_peer_data in `_on_s3_credential_gone` function, and this causes described issue.

### LINKED ISSUE #562: Cannot restore PITR if the new cluster has a different app name from the one the backup was performed from
## Steps to reproduce

1. Deploy the PostgreSQL charm with the application name equal to `postgresql`.
2. Deploy the S3 integrator charm, configure it and relate it to the `postgresql` application.
3. Create a backup, then write some data and later create another backup.
5. Remove the `postgresql` application.
6. Deploy a new PostgreSQL charm with the application name equal to `db`.
7. Relate it to the S3 integrator application and trigger a PITR with `juju run db/leader restore restore-to-time="latest" --wait=1000s`.

## Expected behavior
Restore is successfully completed, and the unit has a status equal to `Move restored cluster to another S3 bucket`.

## Actual behavior

Restore fails, and the unit has a status equal to `cannot restore PITR, juju debug-log for details`.

## Versions

Operating system: Ubuntu 24.04 LTS

Juju CLI: 3.4.5-genericlinux-amd64

Juju agent: 3.4.5

Charm revision: 444

LXD: 5.21.2 LTS

## Log output

Juju debug log: 

```sh
unit-db-0: 23:34:35 ERROR unit.db/0.juju-log Restore failed: database service failed to reach point-in-time-recovery target. You can launch another restore with different parameters
unit-db-0: 23:34:35 ERROR unit.db/0.juju-log Can't tell last completed transaction time
```

## Additional context

The issue happens because the stanza name contains the name `postgresql` (from the previous PostgreSQL charm deployment), and the new application is using its application name (`db`) to search for a stanza from which it can perform the PITR.

### LINKED ISSUE #572: Scaling breaks "The S3 repository has backups from another cluster" blocked status
## Steps to reproduce

1. juju deploy s3-integrator
2. juju deploy postgresql --config profile=testing --channel edge
3. _configure s3-integrator to use bucket with backups from another cluster_
4. juju integrate s3-integrator postgresql
5. as it should be, cluster became in `The S3 repository has backups from another cluster` blocked status
    Screenshot
6. juju add-unit postgresql
7. after adding unit (scaling), cluster loose it's blocked status and became active idle
    Screenshot

## Expected behavior
Cluster should keep it's blocked status `The S3 repository has backups from another cluster` even after scaling.

## Actual behavior

See step 7.

## Versions

Operating system: Ubuntu 24.04 LTS

Juju CLI: 3.5.3-genericlinux-amd64

Juju agent: 3.5.2

Charm revision: 454

LXD: 6.1

## Log output

Juju debug log: [debug-log](https://github.com/user-attachments/files/16501446/new_issue_vm.log)

## Additional context

Here the message I've already wrote in K8s issue:
> From the work on [Point In Time Recovery](https://github.com/canonical/postgresql-k8s-operator/pull/554), i can suggest to refactor logic of this blocked message. Now, `The S3 repository has backups from another cluster` message sets in `PostgreSQLBackups._on_s3_credential_changed` by `can_use_s3_repository` func and it's supposed not to be overridden by any of events. But it's better to keep this status in `app_peer_data` and set this message in `PostgresqlOperatorCharm._set_active_status` function as it works with blocked status `Move restored cluster to another S3 bucket` introduced by the PITR work in the PR referenced above.

### LINKED ISSUE #576: Error initializing stanza after relating to the S3 integrator (with backups from another cluster) and the Juju leader unit is not the PostgreSQL primary
## Steps to reproduce

1. Deploy 3 units of PostgreSQL
2. Switch primary to the another unit (`curl -X POST -d '{"leader": "postgresql-0", "candidate": "postgresql-1"}' -H "Content-Type: application/json" http://<primary_ip>:8008/switchover`)
  Знімок екрана з 2024-08-07 14-33-56
3. Relate charm with s3-integrator, that have backups from another cluster
4. Observe error
  Знімок екрана з 2024-08-07 14-34-16

## Expected behavior
Cluster should appear in "The S3 repository has backups from another cluster" blocked message.

## Actual behavior

See step 4.

## Versions

Operating system: Ubuntu 24.04 LTS

Juju CLI: 3.5.3-genericlinux-amd64

Juju agent: 3.5.3

Charm revision: 454

LXD: 6.1

## Log output

Juju debug log: [vm_issue_s3_primary_leader_desync.log](https://github.com/user-attachments/files/16539766/vm_issue_s3_primary_leader_desync.log)

pgBackRest error (k8s issue i have mentioned on the beginning have the same issue, but more detailed logs):
```
unit-postgresql-1: 14:34:09 ERROR unit.postgresql/1.juju-log s3-parameters:4: ERROR: [028]: backup and archive info files exist but do not match the database
       HINT: is this the correct stanza?
       HINT: did an error occur during stanza-upgrade?

unit-postgresql-1: 14:34:10 INFO juju.worker.uniter.operation ran "s3-parameters-relation-changed" hook (via hook dispatching script: dispatch)
```

## Additional context

This issue is tightly related to the https://github.com/canonical/postgresql-operator/issues/330, though @marceloneppel recommended to create distinct issue, as original issue implies using clear s3-integrator and here are somewhat different steps to reproduce issue and the error itself.

I've checked S3 relation code and found the next issue:
In `def _on_s3_credential_changed(self, event: CredentialsChangedEvent)` func, we have check for the primary:
```
        # Verify the s3 relation only on the primary.
        if not self.charm.is_primary:
            return
```
But function `def can_use_s3_repository(self) -> Tuple[bool, Optional[str]]`, that should verify is S3 stanza eligible to work with before initializing it, really do the check only if the unit is the leader:
```
        if self.charm.unit.is_leader():
            for stanza in json.loads(stdout):
```
So, when leader / primary is in desync, S3 relation code just not works properly.

### PR DESCRIPTION
**Pull request by Zvirovyi**
~Based on the [Timeline Management PR](https://github.com/canonical/postgresql-operator/pull/629).~
Includes improvements from the https://github.com/canonical/postgresql-k8s-operator/pull/690.
~I've currently disabled failing unit tests and will fix them after this PR is reviewed.~
Fixes #576. Fixes #572. Fixes #562. Fixes #463.

Overhauls s3 initialization sequence to support leader / primary desync through multiple units.
Introduces the next fields in the app peer data / unit peer data:
* `s3-initialization-start`: the s3 initialization sequence started (only leader) and waiting for it to complete.
* `s3-initialization-block-message`: the s3 initialization error. If it is set, then s3 initialization sequence is interrupted, therefore `s3-initialization-start` and `stanza` are empty. If initialization is ran on desynced primary, it can emerge along with the `s3-initialization-done`.
* `s3-initialization-done`: initialization sequence complete (along with the `stanza`) or interrupted (along with the `s3-initialization-block-message`). Refers mainly to the desynced primary. Also emerges on the leader after successful sync of initialization sequence result from the primary (signalizes primary that it safe to remove local result in the unit peer data).

I showcased basic algorithm on the diagram below:
image

### CODE REVIEW

**Review by lucasgameiroborges — APPROVED** [review]
Thanks for porting https://github.com/canonical/postgresql-k8s-operator/pull/690 to here! LGTM from what I can see, no blocking comments on my part :) (just needing the unit tests back ofc)

**Review by marceloneppel — APPROVED** [review]
LGTM! Thanks for the fixes and improvements, @Zvirovyi!

**Review by taurus-forever — APPROVED** [review]
@Zvirovyi please remove from PR description: `I've currently disabled failing unit tests and will fix them after this PR is reviewed.` as I can see unit tests are currently passing well.

**Comment by dragomirp** [comment]
> as I can see unit tests are currently passing well.

That's because the immediately return.

**Comment by Zvirovyi** [comment]
Yes, I will add unit tests today

**Comment by Zvirovyi** [comment]
Everything is done!
I've also implemented model uuid constraint for the S3 stanza according to the DA123.

**Review by marceloneppel — APPROVED** [review]
LGTM! I executed all the backup tests, including manually testing the scenarios from the issues that were fixed. Everything is working fine. Amazing work, @Zvirovyi!

**Pull request merged**
