### PR TITLE
[DPE-6042] Make tox commands resilient to white-space paths

### PR DESCRIPTION
**Pull request by sinclert-canonical**
This PR fixes [tox.ini](https://github.com/canonical/postgresql-operator/blob/main/tox.ini) commands when the repository is cloned on a white-space containing path. The proposed approach quotes the paths where they are defined (central place), instead of where they are used (distributed throughout the file). However, we could go with the other approach if preferred.

### How to reproduce:
```shell
$ mkdir -p "Projects/Canonical/Data Platform/PostgreSQL"
$ cd "Projects/Canonical/Data Platform/PostgreSQL"
$ git clone https://github.com/canonical/postgresql-operator
$ cd postgresql-operator
$ tox run -e format
> ...
> /Users/<USERNAME>/Projects/Canonical/Data:1:1: E902 No such file or directory (os error 2)
> Platform/PostgreSQL/postgresql-operator/src:1:1: E902 No such file or directory (os error 2)
> Platform/PostgreSQL/postgresql-operator/tests:1:1: E902 No such file or directory (os error 2)

```

### Additional considerations
Using the quoted paths to set up the `PYTHONPATH` does not work. This can be tested by running the unit tests.

### References
- [Issue](https://github.com/tox-dev/tox/issues/121#issuecomment-407531282), from the tox repository.
- [Recommended approach](https://github.com/tox-dev/tox/issues/924#issuecomment-1396858349), from the tox repository.

### CODE REVIEW

**Review by marceloneppel — CHANGES_REQUESTED** [review]
Great job, @sinclert-canonical! I saw that the unit tox environment still fails because it has another path variable in the following command:
```sh
poetry run coverage run --source={[vars]src_path} \
        -m pytest -v --tb native -s {posargs} {[vars]tests_path}/unit
```

**Comment by sinclert-canonical** [comment]
I am confused. Both `{[vars]src_path}` and `{[vars]tests_path}` parts of the command are quoted already.

Running the unit test command locally, in this branch, works, as well as the CI job associated with this changes ([reference](https://github.com/canonical/postgresql-operator/actions/runs/11893037076/job/33160640023)). Could you share the CLI entry-point you are executing to that failure?

**Review by marceloneppel — APPROVED** [review]
Sorry, I believe that in one of my tests yesterday I probably forgot to checkout the PR branch again. Now it's working.

**Review by dragomirp — APPROVED** [review]

**Comment by dragomirp** [comment]
> Just FYI: I think this tiny fix could be applied to, literally, all the MySQL / PostgreSQL codebases. So, if you agree if the chosen approach, prepare for a **myriad of tiny PRs** 😄

Yes, do you have a list of all the repos to tweak?

**Pull request merged**
